Css three column layout-David Gonzalez
David-Gonzalez11/c0122-code-solutions pull request #19
Opened 2022-01-29 00:44 UTC by David-Gonzalez11

<img width="1430" alt="3 column" src="https://user-images.githubusercontent.com/24907191/151639787-23bcac0b-b067-40c8-b7a6-c95e65084e16.png">

2022-01-31 17:34 UTC, codingcodymiller requested changes
Hey David, this does not match the example, please revise and submit a new screenshot with your revision.

2022-02-01 06:15 UTC, David-Gonzalez11 commented
![3 column](https://user-images.githubusercontent.com/24907191/151921295-571c98aa-d9e1-4e9c-907d-79061e4707c4.png)

2022-02-01 18:23 UTC, codingcodymiller requested changes
Please make sure to compare your output to the example and look for differences before submitting a new version
![image](https://user-images.githubusercontent.com/32880187/152027899-9942512c-57d2-4e17-8e91-569193cca7a6.png)

2022-02-07 17:36 UTC, David-Gonzalez11 commented
<img width="1048" alt="updated three column" src="https://user-images.githubusercontent.com/24907191/152841645-0e636fea-a931-40f9-8d6a-291816b63623.png">

2022-02-14 02:18 UTC, thebearingedge requested changes

2022-02-14 02:18 UTC, thebearingedge commented on css-three-column-layout/index.html
> +        <div class="columnright">
Try changing your CSS so that you only need one column class instead of qms, middle, and right.

2022-02-14 02:37 UTC, thebearingedge approved these changes

2022-02-14 02:49 UTC, merged