Completed css-four-column-layout-David Gonzalez
David-Gonzalez11/c0122-code-solutions pull request #31
Opened 2022-02-03 17:29 UTC by David-Gonzalez11

![4 column](https://user-images.githubusercontent.com/24907191/152396279-d9541def-7e24-4f58-b95f-a9ef838bbcb8.png)

2022-02-04 19:42 UTC, codingcodymiller requested changes
Hey David, the font family in your output does not match the example, please revise and submit a new screenshot with your revision.

2022-02-09 03:17 UTC, David-Gonzalez11 commented
![new css four-column](https://user-images.githubusercontent.com/24907191/153115336-4021b461-d0e2-475c-a352-5cdfff8acc45.png)

2022-02-14 02:19 UTC, thebearingedge requested changes

2022-02-14 02:19 UTC, thebearingedge commented on css-four-column-layout/index.html
> +        </div>
Please restructure your document so that each column contains an image, a heading, and a paragraph.

2022-02-14 03:20 UTC, thebearingedge approved these changes

2022-02-14 03:21 UTC, merged