Css ecommerce page-David Gonzalez
David-Gonzalez11/c0122-code-solutions pull request #36
Opened 2022-02-06 21:53 UTC by David-Gonzalez11

![Uploading ecommerce.png…]()

2022-02-07 19:00 UTC, David-Gonzalez11 commented
<img width="1020" alt="ecommerce" src="https://user-images.githubusercontent.com/24907191/152853904-2a825f95-f2af-46ba-9a58-3ff86bb313a7.png">

2022-02-07 21:10 UTC, codingcodymiller requested changes
Hey David, the text below each item doesn't match the example in multiple ways, please examine them closely and submit a new version with a new screenshot.

2022-02-09 04:25 UTC, David-Gonzalez11 commented
![new ecommerce](https://user-images.githubusercontent.com/24907191/153121742-651bfbf9-141a-46ad-99ac-15ac55a1f4a3.png)

2022-02-14 02:20 UTC, thebearingedge requested changes

2022-02-14 02:20 UTC, thebearingedge commented on css-ecommerce-page/index.html
> +          </p>
Try restructuring your CSS so that all of your column divs just have a percentage width of 20% and a little bit of left/right padding.

2022-02-14 03:17 UTC, thebearingedge approved these changes

2022-02-14 03:21 UTC, merged