String manipulation 1
David-Gonzalez11/c0122-code-solutions pull request #43
Opened 2022-02-09 05:06 UTC by David-Gonzalez11

<img width="907" alt="string manipulation 1" src="https://user-images.githubusercontent.com/24907191/153125607-58dea87a-3cb6-411a-97cb-137994865012.png">

2022-02-09 15:56 UTC, thebearingedge requested changes

2022-02-09 15:56 UTC, thebearingedge commented on string-manipulation-1/src/is-vowel.js
> +  if (char === 'A' || char === 'a' || char === 'E' || char === 'e' || char === 'I' || char === 'i' || char === 'O' || char === 'o' || char === 'U' || char === 'u') {
If you make the character lowercased first, one time, then you can check half as many comparisons.

```js
var lowerChar = char.toLowerCase();
```

2022-02-14 02:22 UTC, thebearingedge requested changes

2022-02-14 02:22 UTC, thebearingedge commented on string-manipulation-1/src/is-vowel.js
> +    char === 'u'
As written, this only handles these 5 specific characters, but it should be able to handle _all_ vowels in upper or lowercase. So I recommend comparing the lowercased character only.

2022-02-21 18:23 UTC, codingcodymiller approved these changes

2022-02-21 18:59 UTC, merged