Dom event delegation
David-Gonzalez11/c0122-code-solutions pull request #47
Opened 2022-02-11 06:32 UTC by David-Gonzalez11

![dom-event-delegation](https://user-images.githubusercontent.com/24907191/153546932-cc8b4937-c738-430c-8d05-78de8f92f3fb.png)

2022-02-11 15:26 UTC, thebearingedge requested changes

2022-02-11 15:26 UTC, thebearingedge commented on dom-event-delegation/main.js
> +  console.log('closest: . task-list-item', taskListItem);
you also need to remove that taskListItem

2022-02-11 16:14 UTC, David-Gonzalez11 commented on dom-event-delegation/main.js
> +  console.log('closest: . task-list-item', taskListItem);
<img width="452" alt="new dom delegation" src="https://user-images.githubusercontent.com/24907191/153627645-26d3f240-b78a-4800-8798-a5d43914a83e.png">

2022-02-14 03:15 UTC, thebearingedge approved these changes

2022-02-14 03:22 UTC, merged