Completed html-forms exercise-david Gonzalez
David-Gonzalez11/c0122-code-solutions pull request #7
Opened 2022-01-26 00:37 UTC by David-Gonzalez11

![form](https://user-images.githubusercontent.com/24907191/151083182-e70081bc-efc6-4f56-877e-efdf442b40aa.png)

2022-01-26 17:12 UTC, codingcodymiller requested changes

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="Email">Email</label>
This `label` is not properly configured to connect with its form control element. Make sure that the `for` and `id` attribute values match.

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="Why coding">Why is coding cool?</label>
This `label` is not properly configured to connect with its form control element. Make sure that the `for` and `id` attribute values match. Also, no spaces in the value here, that means multiple values

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="Favorite Language">Favorite Language(choose one) </label>
This `label` is not properly configured to connect with its form control element. Make sure that the `for` and `id` attribute values match. Also, no spaces in the value here, that means multiple values

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="Sign me up!" >Sign me up!</label>
This `label` is not properly configured to connect with its form control element. Make sure that the `for` and `id` attribute values match. Also, no spaces in the value here, that means multiple values

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="submit"></label>
If it's empty, there is no need for a `label` element

2022-01-26 17:12 UTC, codingcodymiller commented on html-forms/index.html
> +          <label for="comments">Comments</label>
This `label` is not properly configured to connect with its form control element. Make sure that the `for` and `id` attribute values match.

2022-01-28 08:06 UTC, David-Gonzalez11 commented on html-forms/index.html
> +          <label for="comments">Comments</label>
https://user-images.githubusercontent.com/24907191/151510197-30f5c829-d6d7-4305-a7e7-9a39d7ff8871.mov

2022-01-28 18:19 UTC, codingcodymiller requested changes

2022-01-28 18:19 UTC, codingcodymiller commented on html-forms/index.html
> +          <select id="Why coding">
`id` values can not have spaces, you should use `kebab-case`

2022-01-28 22:44 UTC, codingcodymiller requested changes

2022-01-28 22:44 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="Favorite Language">Favorite Language(choose one)</label>
Make sure you check if anything else needs to be changed with the same problem when you get feedback 👀

2022-01-28 22:44 UTC, codingcodymiller commented on html-forms/index.html
> +            id="Favorite Language" />HTML
Make sure you check if anything else needs to be changed with the same problem when you get feedback 👀

2022-01-28 22:44 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="checkbox" name="SignUp!" id="Sign me up" />
Make sure you check if anything else needs to be changed with the same problem when you get feedback 👀

2022-01-28 22:44 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="Sign me up">Sign me up!</label>
Make sure you check if anything else needs to be changed with the same problem when you get feedback 👀

2022-01-31 17:22 UTC, codingcodymiller requested changes

2022-01-31 17:22 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="Sign me up">Sign me up!</label>
This still needs to be addressed. Spaces are not allowed in `id` values

2022-02-03 20:47 UTC, codingcodymiller approved these changes

2022-02-04 01:29 UTC, merged